variable "asg_image_id" {}
variable "asg_instance_type" {}
variable "asg_availability_zone" {}
variable "asg_max_size" {}
variable "asg_min_size" {}
variable "asg_desire_capacity" {}
variable "demo_tg_arn" {}
variable "public_subnet" {}
variable "web_sg" {}